name: Maven Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Give execute permission to mvnw
      run: chmod +x mvnw
    - name: Install Maven
      run: sudo apt-get update && sudo apt-get install -y maven

    - name: Build with Maven Wrapper
      run: mvn clean package -Dmaven.test.skip=true

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_DEST: ${{ secrets.SERVER_DEST }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $SERVER_HOST >> ~/.ssh/known_hosts
        scp target/your-artifact.jar $SERVER_USER@$SERVER_HOST:$SERVER_DEST
        ssh $SERVER_USER@$SERVER_HOST "sudo systemctl restart your-service"
